### ISSUE TITLE
 Could not find or load main class se.gustavkarlsson.rocketchat.jira_trigger.App

### ISSUE THREAD

**Issue by brady-young** [gustavkarlsson/rocketchat-jira-trigger#30]
I performed your steps to install the rocketchat-jira-trigger and when I go to run the command: ./rocketchat-jira-trigger config.toml i get the following output:  Could not find or load main class se.gustavkarlsson.rocketchat.jira_trigger.App

**Comment by gustavkarlsson** [comment]
Thanks for letting me know. I'll have a look when I get home from work!

**Comment by gustavkarlsson** [comment]
I cannot recreate the error when I follow the instructions. Can you run these commands in sequence and post the exact output?

```
git clone https://github.com/gustavkarlsson/rocketchat-jira-trigger.git
cd rocketchat-jira-trigger
./gradlew installDist
cd build/install/rocketchat-jira-trigger
bin/rocketchat-jira-trigger config.toml
```
Don't worry about errors such as
```
java.lang.RuntimeException: java.io.FileNotFoundException: config.toml (No such file or directory)
```
That's just the config file missing. It's actually good news since it proves that the main class was loaded and executed.

**Comment by brady-young** [comment]
Thank you for your quick response.  Let me give that a try and I’ll let you know shortly.

**Comment by brady-young** [comment]
What directory do I need to do these commands?

**Comment by gustavkarlsson** [comment]
The commands I posted can be run from anywhere. What issues are you experiencing?

**Comment by brady-young** [comment]
Ok.  I just wanted to make sure.  I’m not experiencing any errors. What directory should I put the config.toml file in?  I just put in /rocketchat-jira-trigger/build/install/rocketchat-jira-trigger

**Comment by brady-young** [comment]
Now it’s just sitting here after running that last command.

# bin/rocketchat-jira-trigger config.toml
13:13:40.977 [main] INFO  s.g.rocketchat.jira_trigger.App - Initializing
13:13:40.980 [main] INFO  s.g.r.j.RestClientProvider - Creating JIRA client
13:13:40.980 [main] INFO  s.g.r.j.RestClientProvider - Getting authentication handler
13:13:40.980 [main] INFO  s.g.r.j.RestClientProvider - Using basic authentication
13:13:40.980 [main] INFO  s.g.r.j.RestClientProvider - Password provided through configuration
13:13:41.870 [main] INFO  s.g.rocketchat.jira_trigger.App - Setting up server
13:13:41.900 [main] INFO  s.g.rocketchat.jira_trigger.App - Server setup completed
13:13:41.921 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @1582ms
13:13:41.992 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...
13:13:41.992 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4567
13:13:41.996 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.3.6.v20151106
13:13:42.052 [Thread-1] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@52b9f467{HTTP/1.1,[http/1.1]}{0.0.0.0:4567}
13:13:42.052 [Thread-1] INFO  org.eclipse.jetty.server.Server - Started @1716ms

**Comment by gustavkarlsson** [comment]
Well, it looks to me like it's running now. If configured correctly, it should respond to requests from your outgoing rocketchat webhook.

**Comment by brady-young** [comment]
Ok great.  Thank you for your help.  Do I just leave it running here?

# bin/rocketchat-jira-trigger config.toml
13:29:17.903 [main] INFO  s.g.rocketchat.jira_trigger.App - Initializing
13:29:17.908 [main] INFO  s.g.r.j.RestClientProvider - Creating JIRA client
13:29:17.908 [main] INFO  s.g.r.j.RestClientProvider - Getting authentication handler
13:29:17.909 [main] INFO  s.g.r.j.RestClientProvider - Using basic authentication
13:29:17.909 [main] INFO  s.g.r.j.RestClientProvider - Password provided through configuration
13:29:18.721 [main] INFO  s.g.rocketchat.jira_trigger.App - Setting up server
13:29:18.745 [main] INFO  s.g.rocketchat.jira_trigger.App - Server setup completed
13:29:18.764 [Thread-1] INFO  org.eclipse.jetty.util.log - Logging initialized @1532ms
13:29:18.825 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - == Spark has ignited ...
13:29:18.825 [Thread-1] INFO  s.e.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:4567
13:29:18.829 [Thread-1] INFO  org.eclipse.jetty.server.Server - jetty-9.3.6.v20151106
13:29:18.883 [Thread-1] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@30447620{HTTP/1.1,[http/1.1]}{0.0.0.0:4567}
13:29:18.883 [Thread-1] INFO  org.eclipse.jetty.server.Server - Started @1654ms

Or can I CTRL+C so I can use the command line?

**Comment by gustavkarlsson** [comment]
Yes. The rest is done in rocketchat. You can check  the terminal window for activity to see if it's doing something.
