### ISSUE TITLE
Improve Log readability 

### ISSUE THREAD

**Issue by PPPBerlin** [gustavkarlsson/rocketchat-jira-trigger#33]
rocketchat_logger rocketchat_logger.js:377 Integrations ➔ Outgoing WebHook.info Will be executing the Integration "JIRA" to the url: http://172.18.0.7:4567/
 rocketchat_logger rocketchat_logger.js:377 Integrations ➔ Outgoing WebHook.info Status code for the Integration JIRA to http://172.18.0.7:4567/ is 200

This log entry spam into the main-log of rocket.chat. 

it would be nice to disable it.

**Comment by gustavkarlsson** [comment]
Since this is regarding rocket.chat itself you would have to create an issue on the rocket.chat project instead. I can't do anything about it.
