### ISSUE TITLE
Wrong encoding in the Preview

### ISSUE THREAD

**Issue by PPPBerlin** [gustavkarlsson/rocketchat-jira-trigger#35]
Hi,

found this yesterday. 

An apostroph in title is shown as "&#39;" in the Preview. Looks like an encoding issue to me.

![image](https://cloud.githubusercontent.com/assets/23475627/25758016/2844cdb0-31cd-11e7-887c-52bd246bd8b0.png)

I place an apostrophe for testing on the end of the title.

**Comment by gustavkarlsson** [comment]
I have also noticed this issue recently. The JIRA API represents special characters as HTML escape codes. It should pretty simple to unescape them before sending them back to Rocket.Chat

**Comment by PPPBerlin** [comment]
Hi, did you still work on this issue?

**Comment by gustavkarlsson** [comment]
I've been busy lately, but I intend to get back to it pretty soon.

**Comment by PPPBerlin** [comment]
Hi, i pull the last docker image and see no change in that issue. Tan i notice, that your docker builds failed since 2 month.
Build failed: The command '/bin/sh -c mkdir /app && ./gradlew installDist && cp -R build/install/rocketchat-jira-trigger/* /app && cd / && rm -rf /root/.gradle && rm -rf /src' returned a non-zero code: 1

**Comment by gustavkarlsson** [comment]
I don't know what caused the failed builds, but I've been pushing my own builds to docker-hub lately instead, maybe I made a mistake there... I'll have to look into this again....

**Comment by gustavkarlsson** [comment]
I took a deeper look and managed to reproduce the problem. Apparently the issue is on the Rocket.Chat side, so there's nothing I could do...
