### ISSUE TITLE
Show Issues only when it stands alone.

### ISSUE THREAD

**Issue by PPPBerlin** [gustavkarlsson/rocketchat-jira-trigger#36]
One developer found minor issue. If you have have a i.e a filename like PROJ-54_b02_bla.jpg, the bot will also show you the Issue Information. But he should not. So it would be greate if you check, if there is i.e. a space before and behind the Issue. That should also fix the problem, that you get per default the Link Preview and the information from the bot, after you paste the complete Link.

Thanks for your work!

**Comment by gustavkarlsson** [comment]
I see your point, but that would also make it ignore URL:s to the actual JIRA-issues (which is something we DO want to show a summary of). I don't think false positives like the one you found are very common.

It's hard to find a good balance between false negatives and false positives, but in this case I think the simplest solution (match any occurrence regardless of context) is also the best.

**Comment by gustavkarlsson** [comment]
This has been fixed in the newly released 1.1.0
