### ISSUE TITLE
Disable detection in URL:s

### ISSUE THREAD

**Issue by gustavkarlsson** [gustavkarlsson/rocketchat-jira-trigger#39]
Since rocket.chat already has an AutoLinker feature, pasting JIRA URL:s will trigger both the AutoLinker and the JIRA summary. This can easily get spammy, and there should be an option to disable detection for URL:s

**Comment by gustavkarlsson** [comment]
Should be combined with: #36

**Comment by pathikb** [comment]
Is there a way to enable this? The AutoLinker is not able to generate JIRA link preview for us and I would like a JIRA reference via a URL (for eg: user posting http://jira.mycompany.com/browse/INC-251) to also trigger this webhook. Is there a way to enable this (I could do it in my forked copy if you wouldn't like to have this).

**Comment by gustavkarlsson** [comment]
Try setting:
```
[message]
whitelisted_jira_key_prefixes = "([{<:/"
```
`whitelisted_jira_key_prefixes` is a list of all characters that may appear before a JIRA key for it to be detected. I've added '/' to the defaults, which should enable URL:s like yours.
