### ISSUE TITLE
Allow triggering on message attachements (i.e. from other bots)

### ISSUE THREAD

**Issue by Bubu** [gustavkarlsson/rocketchat-jira-trigger#40]
We have the following use case:

* Rocketchat receives an incoming webhook whenever someone pushes something to our gitlab repositories. (The integration can be found here: https://github.com/malko/rocketchat-gitlab-hook)
* A rocketchat bot posts a message containing a summary for each pushed commit. This often includes references to jira tickets.
* Now it would be really nice if the jira bot can fetch the issue summaries and link to them whenever such a commit message is send to rocketchat

At the moment this does not work, even though I have removed the gitlab bot from the blacklisted users. I think this is because everything gets posted as an attachment and is not processed by the jira trigger service?

**Comment by gustavkarlsson** [comment]
You're correct. It only considers text in the main message.
However, this sounds like a reasonable suggestion. I'll look into it!

**Comment by gustavkarlsson** [comment]
Rocket.Chat doesn't seem to send the attachment data, so there's currently no way to accomplish this.
