### ISSUE TITLE
Use environment variables for configuration

### ISSUE THREAD

**Issue by eloo** [gustavkarlsson/rocketchat-jira-trigger#42]
It would be great if we could provide some configs via env variables.
Like the password for example.

**Comment by gustavkarlsson** [comment]
I'm not directly opposed to the idea, and I think it's pretty trivial to add, but what problem does it actually solve?

If you don't want your password in a file, you can leave it out and provide it (in a safe way) at the password prompt.

**Comment by Eloo** [comment]
i'm using your docker image in a kubernetes enviroment and i dont want to need manually enter the password everytime the pod is recreated ;)
and adding the password in plaintext into the config.toml isn't a secure choice as we want to persist this in a git repo ;)

**Comment by gustavkarlsson** [comment]
I almost suspected some kind of docker answer, and I've recently become a fan of the [Twelve-Factor App](https://12factor.net/config) which makes a good argument for using env variables for configuration.

I'll consider it :)

**Comment by gustavkarlsson** [comment]
Update: I am working on this, but it might still take some time until it's released.

**Comment by gustavkarlsson** [comment]
Please try out [1.3.0](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.3.0) where this should be fixed :)

**Comment by eloo** [comment]
@gustavkarlsson 
yeah that looks quite good 
thanks

**Comment by gustavkarlsson** [comment]
@eloo let me know if you run into any more issues.
