### ISSUE TITLE
problem generating proper links when uri contains "/"

### ISSUE THREAD

**Issue by wysockip** [gustavkarlsson/rocketchat-jira-trigger#47]
Hi,

Don't know if this is a configuration problem or source problem but when we have like:
https://internal/jira as the uri and we run the intergration we end up with the RocketChat message which is showing link like https://internal/browse/ABC-1 instead of https://internal/jira/browse/ABC-1

Any chance to fix / advice?

Cheers
Pawel

**Comment by gustavkarlsson** [comment]
Sounds like a bug. I'll have a look.

**Comment by wysockip** [comment]
Thanks for answer. Would be lovelly to have this fixed, especially for ppl which are hosting all the stuff internally behind nginx/apache.

**Comment by gustavkarlsson** [comment]
Yeah. I understand the issue. I might be able to have it fixed today. No promises thought!

**Comment by gustavkarlsson** [comment]
@wysockip Just an update. Obviously I didn't fix this thing yet (sorry), but I have a solution in the works that should resolve it. Hopefully I'll find some time to merge it soon. Hang in there!

**Comment by wysockip** [comment]
Thanks for update.

**Comment by shakalandy** [comment]
Would also be interested in a fix here.
Where to donate? :)

**Comment by gustavkarlsson** [comment]
@shakalandy wow, you flatter me.

No donations, but I'll see if I can't put in some effort over the weekend.

**Comment by gustavkarlsson** [comment]
Please try out [1.3.0](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.3.0) where this should be fixed :)

**Comment by shakalandy** [comment]
Works like a charm, thanks!
