### ISSUE TITLE
Excessive error prints in Rocket.Chat logs

### ISSUE THREAD

**Issue by pasmon** [gustavkarlsson/rocketchat-jira-trigger#49]
Great work on the Jira integration!

I just got this setup for our Rocket.Chat, and it is working nicely. I would still like to get rid of all the excessive log prints in Rocket.Chat:

> [34mI20180201-07:19:49.336(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error Error for the Integration "Jira" to http://jira-trigger:4567/ is: 
> [34mI20180201-07:19:49.337(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error { statusCode: 204,   content: '',   headers:     { connection: 'close',      date: 'Thu, 01 Feb 2018 07:19:49 GMT',      'content-type': 'text/html;charset=utf-8',      server: 'Jetty(9.4.4.v20170414)' },   data: null } 
> [34mI20180201-07:19:49.467(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error Error for the Integration "Jira" to http://jira-trigger:4567/ is: 
> [34mI20180201-07:19:49.467(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Outgoing WebHook.error { statusCode: 204,   content: '',   headers:     { connection: 'close',      date: 'Thu, 01 Feb 2018 07:19:49 GMT',      'content-type': 'text/html;charset=utf-8',      server: 'Jetty(9.4.4.v20170414)' },   data: null }
> 

I think these prints come every time anybody says something in chat, without mentioning any Jira issue.

Could this be disabled in the outgoing webhook integration script?

Rocket.Chat version: 0.60.4 running in Docker

**Comment by gustavkarlsson** [comment]
> I think these prints come every time anybody says something in chat

Yes, that's correct.

> Could this be disabled in the outgoing webhook integration script?

Yes I believe so. You can try creating your own "filter" so to speak by only sending messages that match a certain pattern, but you're on your own when it comes to setting that up. Check the [rocket.chat Gitter](https://gitter.im/RocketChat/Rocket.Chat) and see if they can help.

**Comment by gustavkarlsson** [comment]
@pasmon Turns out what you were seeing was NOT actually normal. Rocket.Chat was spamming the integration because it didn't consider the responses to no-jira messages acceptable.

I've just released a bugfix which should fix this and greatly reduce network load. The errors should go away with the latest [release](https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases).
