### ISSUE TITLE
Bot message cropped in iOS app

### ISSUE THREAD

**Issue by cvoelz** [gustavkarlsson/rocketchat-jira-trigger#50]
Hi,

we noticed a displaying problem when using the latest iOS Swift App (1.80). 
The message from the jira bot gets cropped, only the "assigned to" field is visible. 

![img_5579](https://user-images.githubusercontent.com/16133905/36150237-450e844c-10c3-11e8-924a-b47ed6a3b634.jpg)

There aren't any options for message display in the app, but it was working fine in the last version. 
Any idea how to fix that? 

Thankys for your effort!

**Comment by gustavkarlsson** [comment]
I'm sorry but this is an issue for the iOS app. I have no control over how messages are displayed on iOS.

Please post your question over at https://github.com/RocketChat/Rocket.Chat.iOS instead :)
