### ISSUE TITLE
Custom Field support

### ISSUE THREAD

**Issue by HmmWhy** [gustavkarlsson/rocketchat-jira-trigger#55]
Should it support custom fields in Jira?
I've added my custom field name into extended_fields but it will never return them.

**Comment by gustavkarlsson** [comment]
I believe custom fields should work.
`extended_fields` is not meant specifically for custom fields. It's a list of extra fields that are shown when you add a **+** after the JIRA issue key.

Example

> Show me PROJ-2454+

Try a adding your custom field in `default_fields` if you want it to always be shown, and please let me know if it worked or not :)

**Comment by HmmWhy** [comment]
I had tried both fields and I just can't get it to pull a custom one, I know it is picking up the string as if i drop a standard field from the list, it disappears from the display.

**Comment by gustavkarlsson** [comment]
I've marked this as a bug and will look into it

**Comment by gustavkarlsson** [comment]
Added in https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.4.0
