### ISSUE TITLE
Failed build. Please see error below

### ISSUE THREAD

**Issue by SueZ-Q** [gustavkarlsson/rocketchat-jira-trigger#56]
root@fmgnsgRCtst01:/installs/rocketchat-jira-trigger-1.3.2# ./gradlew installDist
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/installs/rocketchat-jira-trigger-1.3.2/build.gradle' line: 5

* What went wrong:
Error resolving plugin [id: 'com.github.johnrengelman.shadow', version: '1.2.4']
> Could not GET 'https://plugins.gradle.org/api/gradle/4.1/plugin/use/com.github.johnrengelman.shadow/1.2.4'.
   > Connect to plugins.gradle.org:443 [plugins.gradle.org/104.16.175.166, plugins.gradle.org/104.16.172.166, plugins.gradle.org/104.16.173.166, plugins.gradle.org/104.16.174.166, plugins.gradle.org/104.16.171.166] failed: Connection timed out (Connection timed out)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 26s

Any Idea Why?

**Comment by gustavkarlsson** [comment]
Looks like a network problem. Either on your side or at plugins.gradle.org.
Check your connectivity and try again later. Let mw know if it still doesn't work
