### ISSUE TITLE
More than one jira possible?

### ISSUE THREAD

**Issue by PPPBerlin** [gustavkarlsson/rocketchat-jira-trigger#58]
Hi, we find out that it would very useful to have more than one jira to trigger. Is there possibility to do this? Thanks

**Comment by gustavkarlsson** [comment]
Are you talking about running JIRA instances? Can you give an example?

**Comment by PPPBerlin** [comment]
the trigger runs fine for our internal jira and a few colleagues want the same solution for bugreports.qt.io get information about issues from this jira.

**Comment by PPPBerlin** [comment]
But i think, the problem could be where the trigger should search for the issue-code.

**Comment by gustavkarlsson** [comment]
I'm not planning on adding support for this, but as a simple solution you could just run another instance configured for a different JIRA.
