### ISSUE TITLE
Disable hook chronic?

### ISSUE THREAD

**Issue by graphik55** [gustavkarlsson/rocketchat-jira-trigger#60]
Hello,

your integration is a nice peace of software and I hope you can help me to configure it the right way.
If I send a message with an issue numer, like CTI-1322, than I get a response as expected.
This request and all other messages which do not match a Jira issue and are not send to Jira are visible inside the chronic of the integration. 
Is it possible to disable this behavior? I don't want to see the messages of users if they do not try to access Jira.

Hope I could explain what my problem is.

Thanks for your help.
graphik

**Comment by gustavkarlsson** [comment]
Hi, I don't know what you mean by mean chronic, but it sounds like you you are talking about logging?
Are you asking for a way to hide messages from the log output?

Can post a screenshot or something to demonstrate what you mean?

**Comment by graphik55** [comment]
Hey,
thank you for your fast replay.

Yeah logging sounds good. It is also labeld as "history".
And yes I like to hide the messages from there.
Hope the screenshots helps to understand my issue.

![jira_request](https://user-images.githubusercontent.com/38713803/46071424-460c8380-c180-11e8-8e6c-1ca890edf78a.png)
![message_should_hide](https://user-images.githubusercontent.com/38713803/46071425-460c8380-c180-11e8-8ceb-5e766763b9c4.png)
![webhook_settings](https://user-images.githubusercontent.com/38713803/46071426-460c8380-c180-11e8-9ac5-c1e3996fa1c5.PNG)

**Comment by gustavkarlsson** [comment]
I'm sorry but this is out of scope for the integration. If you want to hide rocket.chat logs, you have to consult the rocket.chat documentation or support channels.

**Comment by graphik55** [comment]
Ok good to know.

Thank you for your fast help =D
