### ISSUE TITLE
issue link broken

### ISSUE THREAD

**Issue by toastbrotch** [gustavkarlsson/rocketchat-jira-trigger#64]
seems this line makes troubles at my setup:

https://github.com/gustavkarlsson/rocketchat-jira-trigger/blob/4d78d4a67b8d052aca4b8dda767024f57b06d412/src/main/java/se/gustavkarlsson/rocketchat/jira_trigger/messages/AttachmentCreator.java#L65

as this does not make a html-like issue-url as expected 
`<a href="url">title</a>`
but `&lt;<a href="url|first_word_of_title">url|first_word_of_title</a>rest_of_title&gt;`

any idea where this comes from? autolinker is activated...

**Comment by gustavkarlsson** [comment]
I'm sorry but I don't quite understand what you mean... Could you clarify. What was in the message, and what was the link produced?

**Comment by gustavkarlsson** [comment]
Fixed in https://github.com/gustavkarlsson/rocketchat-jira-trigger/releases/tag/1.4.0

**Comment by toastbrotch** [comment]
awesome! works perfect! thanx
