### ISSUE TITLE
Fetch multiple Isssue on Project 

### ISSUE THREAD

**Issue by MatthiasHertel** [gustavkarlsson/rocketchat-jira-trigger#65]
Hi 

i have a question, it is possible to fetch multiple issues on a jira project ?

Currently i have to name the correct Issue key. There are no matching functionallity ?

e.g.

see the example below , there is a project named TSSD with 2 issues (TSSD-1 and TSSD-2). 
I can fetch the specific Issue by referencing the key ... but i want all issues on the project.

it is possible to fetch TSSD-1 and TSSD-2 with one message ?
do i do something wrong ?

![image](https://user-images.githubusercontent.com/8426566/49271500-3fdf9f80-f46e-11e8-9ba7-d0dfc0759971.png)

**Comment by MatthiasHertel** [comment]
maybe it is a regex for the config.toml

whitelisted_jira_key_suffixes 

there are a `-123456` digit as a suffix .... ?

**Comment by gustavkarlsson** [comment]
Hi. Sorry but this is not currently possible and I have no plans on supporting it.
