### ISSUE TITLE
Missing spaces in Jira link

### ISSUE THREAD

**Issue by lennartgrunau** [gustavkarlsson/rocketchat-jira-trigger#66]
Hi there,

there's a missing space in the jira link which causes rocketchat to render the link invalid.

<link.to.jira/browse/ERR-1337|Just a title>

There should be a space before and after the Vertical bar |.

Happening in current docker release.

Cheers!

![bildschirmfoto 2018-12-12 um 13 06 32](https://user-images.githubusercontent.com/18286724/49868796-c604ca00-fe0e-11e8-997f-1a12389f6092.png)

![bildschirmfoto 2018-12-12 um 13 02 49](https://user-images.githubusercontent.com/18286724/49868675-69a1aa80-fe0e-11e8-907d-7c70189664bd.png)

**Comment by gustavkarlsson** [comment]
What's your version of rocket.chat?

**Comment by lennartgrunau** [comment]
Hi, any news here?
